### ISSUE TITLE
[BUG]: Bind9 in Alpine Linux says `-n` option to `dnssec-dsfromkey` does not exist.

### ISSUE THREAD

**Issue by zenny** [northox/dnssec-reverb#25]
Hi,

Thanks for posting.

Meanwhile, I tried with Bind in Alpine linux with `dnssec-reverb.conf` with the following config:

```
MASTERDIR="/etc/bind/zones/master/"

KEYGEN_CMD="$(which dnssec-keygen)"
SIGNZONE_CMD="$(which dnssec-signzone)"
KEY2DS_CMD="$(which dnssec-dsfromkey)"
CHECKZONE_CMD="$(which named-checkzone)"
CONTROL_CMD="$(which rndc)"
#RELOAD_CMD="(echo -n 'reload is '; $CONTROL_CMD reload) && (echo -n 'notify is '; $CONTROL_CMD notify)"

KSK_PARAM="-n zone -a ECDSAP256SHA256 -f ksk"
ZSK_PARAM="-n zone -a ECDSAP256SHA256 "
SIGN_PARAM="-N increment"
#DS_HASH="2" # 1=SHA1 2=SHA256 3=GOST 4=SHA384
DS_PARAM="-2"

#EXPIRE_DAYS="33"
#ZSK_PARAM_example.net=-a RSASHA1-NSEC3-SHA1
```
the keys were generated, but I got the following error, telling the `-n` option to `dnssec-dsfromkey` command does not exist, fyi:

```
# dnssec-reverb keygen example.net
Generating key pair.
Generating key pair.
New keys created
example.net -- https://dnsviz.net/d/example.net/dnssec/
 type state  id    algo hash (expiration)        (digest)
dnssec-dsfromkey: invalid argument -n
Usage:
    dnssec-dsfromkey [options] keyfile

    dnssec-dsfromkey [options] -f zonefile [zonename]

    dnssec-dsfromkey [options] -s dnsname

    dnssec-dsfromkey [-h|-V]

Version: 9.18.27
Options:
    -1: digest algorithm SHA-1
    -2: digest algorithm SHA-256
    -a algorithm: digest algorithm (SHA-1, SHA-256 or SHA-384)
    -A: include all keys in DS set, not just KSKs (-f only)
    -c class: rdata class for DS set (default IN) (-f or -s only)
    -C: print CDS records
    -f zonefile: read keys from a zone file
    -h: print help information
    -K directory: where to find key or keyset files
    -s: read keys from keyset-<dnsname> file
    -T: TTL of output records (omitted by default)
    -v level: verbosity
    -V: print version information
Output: DS or CDS RRs
 ZSK  active 25997 13    2
```

Thanks.
/zenny

**Comment by zenny** [comment]
@northox bump

**Comment by northox** [comment]
I use and test dnssec-reverb on OpenBSD with NSD. Seems like you use bind.
Please confirm this is addressed by the latest patch or provide your own patch. I will close this issue in 2w if I have no news.

**Comment by zenny** [comment]
> I use and test dnssec-reverb on OpenBSD with NSD. Seems like you use bind. Please confirm this is addressed by the latest patch or provide your own patch. I will close this issue in 2w if I have no news.

@northox Thanks, I came across a bit late. I pulled from master today and tried once again and it still reports the same.

```
# ./dnssec-reverb keygen <example.com>
Generating key pair.
Generating key pair.
New keys created
<example.com> -- https://dnsviz.net/d/<example.com>/dnssec/
 type state  id    algo hash (expiration)        (digest)
dnssec-dsfromkey: invalid argument -n
Usage:
    dnssec-dsfromkey [options] keyfile

    dnssec-dsfromkey [options] -f zonefile [zonename]

    dnssec-dsfromkey [options] -s dnsname

    dnssec-dsfromkey [-h|-V]

Version: 9.18.31
Options:
    -1: digest algorithm SHA-1
    -2: digest algorithm SHA-256
    -a algorithm: digest algorithm (SHA-1, SHA-256 or SHA-384)
    -A: include all keys in DS set, not just KSKs (-f only)
    -c class: rdata class for DS set (default IN) (-f or -s only)
    -C: print CDS records
    -f zonefile: read keys from a zone file
    -h: print help information
    -K directory: where to find key or keyset files
    -s: read keys from keyset-<dnsname> file
    -T: TTL of output records (omitted by default)
    -v level: verbosity
    -V: print version information
Output: DS or CDS RRs
 ZSK  active 26255 13    2
```

Just wondering what is equivalent of the supposedly invalid argument `-n` in bind?

`dnssec-dsfromkey: invalid argument -n`

Thanks for the update, and Cheers,
/zenny

**Comment by northox** [comment]
It's seems you don't need "-n" to send to stdout. With the latest modifications it should be easy to fix.

**Comment by northox** [comment]
Hello @zenny. This should be good now. Please confirm.

**Comment by zenny** [comment]
> Hello @zenny. This should be good now. Please confirm.

@northox Thanks for prompt response, but it still does not seem to work. Says:
`dnssec-dsfromkey: invalid argument --`
 
Verbatim output as of below:

```
# ./dnssec-reverb keygen example.com
Generating key pair.
Generating key pair.
New keys created
example.com -- https://dnsviz.net/d/example.com/dnssec/
 type state  id    algo hash (expiration)        (digest)
dnssec-dsfromkey: invalid argument --
Usage:
    dnssec-dsfromkey [options] keyfile

    dnssec-dsfromkey [options] -f zonefile [zonename]

    dnssec-dsfromkey [options] -s dnsname

    dnssec-dsfromkey [-h|-V]

Version: 9.18.31
Options:
    -1: digest algorithm SHA-1
    -2: digest algorithm SHA-256
    -a algorithm: digest algorithm (SHA-1, SHA-256 or SHA-384)
    -A: include all keys in DS set, not just KSKs (-f only)
    -c class: rdata class for DS set (default IN) (-f or -s only)
    -C: print CDS records
    -f zonefile: read keys from a zone file
    -h: print help information
    -K directory: where to find key or keyset files
    -s: read keys from keyset-<dnsname> file
    -T: TTL of output records (omitted by default)
    -v level: verbosity
    -V: print version information
Output: DS or CDS RRs
 ZSK  active 25417 13    2
```

Cheers.

**Comment by northox** [comment]
I have a new env to test and will be able to test parts of a bind setup locally. Give me a bit of time if you can’t test on your end and send a PR.

**Comment by northox** [comment]
@zenny Here it is. I added a level of testing but it doesn't covers every angle. Let me know if you find anything. I might add the test suite in the repo at some point.
